source/03-AD/04.ptx

closes #25

---

source/05-TI/02.ptx

Fix sin typo

---

source/05-TI/03.ptx

TI3 tweaks

---

source/06-AI/02.ptx

Though probably this should be a tabular, here's a stopgap fix.

closes #63

---

source/04-IN/06.ptx

Add missing primes

---

source/05-TI/06.ptx

Add missing dx in integrals, closes #59

---

exercises/outcomes/LT/LT1/template.xml

The missing element prevented the list item from displaying.

Fix missing <p> in template.xml

---

source/06-AI/01.ptx

Fix typos in activity AI1

---

source/07-CO/01.ptx

Changed some two column multichoice to one column to keep longer answers from overlapping. Changed order of some answers in two columns so they don't overlap.

CO1 Column adjusting Update 01.ptx

---

RATs/RAT-CO.tex

RAT Quiz created for Module CO

RAT Quiz created for Module CO

---

source/07-CO/readiness.ptx

Closes #108 .  Apparently this was introduced in #106 inadvertently.

Fix duplicate xmlids

---

exercises/outcomes/TI/TI4/template.xml

Typo fixes

---

exercises/bank.xml

Addresses #49 by clearly labeling an outcome that requires students to use technology

Add flag about using technology on LT2

---

exercises/outcomes/AD/AD6/generator.sage

closes #42

---

exercises/bank.xml
exercises/outcomes/PS/PS2/generator.sage
exercises/outcomes/PS/PS2/template.xml

Closes #114 .  I added code to randomize the starting index in all cases, but make sure that it doesn't make the denominator zero.

FIx starting index

---

exercises/outcomes/AI/AI3/template.xml

AI3 Checkit template phrasing

---

source/07-CO/01.ptx
source/07-CO/02.ptx
source/07-CO/03.ptx
source/07-CO/04.ptx
source/07-CO/05.ptx
source/07-CO/06.ptx

Add links to videos in CO

---

source/04-IN/06.ptx

Typo fix in IN6 (FTC statement)

---

source/04-IN/08.ptx

Implements helpful suggestions by @owensks and closes #39

Reduce computational complexity of two tasks

---

source/05-TI/08.ptx

This fixes the rest of the issues pointed out in #58 , and as a result closes #58

Fix small typos in TI8

---

source/04-IN/05.ptx

Fix mismatch between task and graph in IN-5

---

source/03-AD/03.ptx

Combine related tasks into one activity in AD3

---

source/08-SQ/03.ptx

address starting index for partial sum

---

exercises/outcomes/AD/AD7/template.xml
source/01-LT/01.ptx
source/01-LT/02.ptx
source/01-LT/03.ptx
source/01-LT/04.ptx
source/01-LT/05.ptx
source/02-DF/01.ptx
source/05-TI/08.ptx

force displaymath for inline limits

---

site/index.html

Add slides link to landing page

---

source/01-LT/05.ptx

Tweak 1.5.14, closes #142
